spring.application.name=VotingManagementSystem

spring.jpa.hibernate.ddl-auto=create
spring.datasource.url=jdbc:mysql://localhost:3306/voting_management_system?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=ahtisham12
spring.jpa.open-in-view=false
spring.sql.init.data-locations=classpath:data.sql
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always